apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: d0ocfe3v6-nodejs 
  janus-idp.io/tekton: d0ocfe3v6-nodejs
  backstage.io/kubernetes-id: d0ocfe3v6-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: d0ocfe3v6-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml