apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: d0ocfe3v6-nodejs
  janus-idp.io/tekton: d0ocfe3v6-nodejs
  backstage.io/kubernetes-id: d0ocfe3v6-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: d0ocfe3v6-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
